import type { MusicCreditGroup } from "./MusicTrackCredits";

const SOCIAL_LABELS = new Set([
  "FOLLOW",
  "FACEBOOK",
  "INSTAGRAM",
  "TWITTER",
  "X",
  "TIKTOK",
  "YOUTUBE",
  "SPOTIFY",
  "APPLE MUSIC",
  "CLICK TO WORSHIP",
  "WORSHIP",
  "STREAM",
  "LISTEN",
  "SHOP",
  "MERCH",
]);

function looksLikeUrl(value: string): boolean {
  const t = value.trim();
  if (!t) return false;
  if (/^https?:\/\//i.test(t) || /^www\./i.test(t)) return true;
  if (/\.(com|net|org|io|to|fm|link)\b/i.test(t) && !/\s/.test(t)) return true;
  return false;
}

function formatRoleLabel(label: string): string {
  return label
    .toLowerCase()
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** Parse YouTube description credit blocks (Provided to YouTube style). */
export function parseYoutubeCreditGroups(description: string | null | undefined): MusicCreditGroup[] {
  const desc = description || "";
  if (!desc) return [];

  const lines = desc.split("\n");
  const groupsMap = new Map<string, string[]>();
  const groupKeys: string[] = [];
  let inCredits = false;
  let inFooter = false;

  for (const line of lines) {
    if (!line.trim()) continue;

    if (line.includes("Auto-generated by YouTube.")) {
      inFooter = true;
      inCredits = false;
      continue;
    }

    if (line.includes(":")) {
      inCredits = true;
      const [rawLabel, ...rest] = line.split(":");
      const label = rawLabel.trim().toUpperCase();
      const value = rest.join(":").trim();
      if (!groupsMap.has(label)) {
        groupsMap.set(label, []);
        groupKeys.push(label);
      }
      groupsMap.get(label)!.push(value);
    } else if (inCredits) {
      inFooter = true;
      inCredits = false;
    } else if (inFooter) {
      // skip footer prose
    }
  }

  return groupKeys.map((k) => ({ label: k, values: groupsMap.get(k)! }));
}

export type CreditPerson = {
  name: string;
  roles: string[];
};

/** People-first credits: drop URL / social rows; merge roles per name. */
export function creditPeopleFromGroups(groups: MusicCreditGroup[]): CreditPerson[] {
  const byName = new Map<string, { name: string; roles: string[] }>();

  for (const group of groups) {
    const labelKey = group.label.trim().toUpperCase();
    if (SOCIAL_LABELS.has(labelKey)) continue;
    const role = formatRoleLabel(group.label);
    for (const raw of group.values) {
      if (looksLikeUrl(raw)) continue;
      const name = raw.trim();
      if (!name) continue;
      const key = name.toLowerCase();
      const existing = byName.get(key);
      if (existing) {
        if (!existing.roles.includes(role)) existing.roles.push(role);
      } else {
        byName.set(key, { name, roles: [role] });
      }
    }
  }

  return [...byName.values()];
}

export function buildNowPlayingCredits(
  groups: MusicCreditGroup[],
  mainArtist: string | null | undefined,
): CreditPerson[] {
  const people = creditPeopleFromGroups(groups);
  const artist = mainArtist?.trim();
  if (!artist) return people;

  const key = artist.toLowerCase();
  const idx = people.findIndex((p) => p.name.toLowerCase() === key);
  if (idx >= 0) {
    const hit = people[idx]!;
    if (!hit.roles.some((r) => /main artist/i.test(r))) {
      hit.roles = ["Main Artist", ...hit.roles];
    }
    if (idx !== 0) {
      people.splice(idx, 1);
      people.unshift(hit);
    }
    return people;
  }

  return [{ name: artist, roles: ["Main Artist"] }, ...people];
}
