import { useMemo } from "react";
import { convertFileSrc } from "@tauri-apps/api/core";
import { ChevronLeft, Play, Youtube, Link } from "lucide-react";
import { useRuforgeStore } from "@/store/ruforgeStore";
import { isAudioOnlyPath, bestCoverPath } from "@/mediaKind";
import { flattenGalleryScanToMediaFiles } from "@/galleryScan";
import { formatDuration } from "@/components/downloader/downloaderFormat";
import type { MediaFile } from "@/types";
import { artistKeyFromFile, rawArtistFromFile } from "./musicArtist";
import { albumKeyFromFile, fileHasBrowsableAlbum } from "./musicShelfDedup";
import { MusicLikeButton } from "./MusicLikeButton";
import type { MusicMetaSidecar } from "@/lib/musicMeta";
import { openInFileManager } from "@/openInFileManager";
import { openUrl } from "@tauri-apps/plugin-opener";
import { canonicalYouTubeWatchUrl } from "@/youtubeUrl";
import { MusicTrackCredits } from "./MusicTrackCredits";
import { musicQueueSource, type MusicQueueSource } from "./musicQueueSource";

function resolveYoutubeWatchUrl(file: MediaFile, meta?: MusicMetaSidecar): string | null {
  for (const candidate of [meta?.youtube?.sourceUrl, file.sourceUrl]) {
    if (!candidate?.trim()) continue;
    const url = canonicalYouTubeWatchUrl(candidate);
    if (url) return url;
  }

  const sourceId = meta?.youtube?.sourceId ?? file.sourceId;
  if (sourceId?.trim()) {
    return canonicalYouTubeWatchUrl(`https://www.youtube.com/watch?v=${sourceId.trim()}`);
  }

  return null;
}

type Props = {
  path: string;
  onPlayFile: (file: MediaFile, playlist: MediaFile[], source: MusicQueueSource) => void;
  onOpenArtist: (artistKey: string) => void;
  onOpenAlbum: (artistKey: string, albumKey: string) => void;
  onBack: () => void;
  meta?: MusicMetaSidecar;
  listenStats?: {
    plays: number;
    lastPlayed: string;
    listenTime: string;
  };
};

function splitCatalogLine(line: string): { title: string; artist?: string } {
  const parts = line.split("·").map((s) => s.trim()).filter(Boolean);
  if (parts.length >= 2) {
    return { title: parts[0]!, artist: parts.slice(1).join(" · ") };
  }
  return { title: line.trim() };
}

function lineDuplicatesCatalog(line: string, catalogTitle: string): boolean {
  const a = line.trim().toLowerCase();
  const b = catalogTitle.trim().toLowerCase();
  if (!a || !b) return false;
  return a === b || b.startsWith(a) || a.startsWith(b);
}

function formatDateString(dateStr: string): string {
  if (!dateStr) return "";
  if (dateStr.length === 8 && /^\d+$/.test(dateStr)) {
    const y = dateStr.slice(0, 4);
    const m = parseInt(dateStr.slice(4, 6), 10) - 1;
    const d = parseInt(dateStr.slice(6, 8), 10);
    const date = new Date(parseInt(y, 10), m, d);
    return date.toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" });
  }
  try {
    return new Date(dateStr).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" });
  } catch {
    return dateStr;
  }
}

export function MusicTrackView({
  path,
  onPlayFile,
  onOpenArtist,
  onOpenAlbum,
  onBack,
  meta,
  listenStats
}: Props) {
  const entries = useRuforgeStore((s) => s.entries);

  const libraryTracks = useMemo(
    () => flattenGalleryScanToMediaFiles(entries).filter((f) => isAudioOnlyPath(f.path)),
    [entries],
  );

  const file = useMemo<MediaFile | null>(() => {
    return libraryTracks.find((f) => f.path === path) ?? null;
  }, [libraryTracks, path]);

  const album = useMemo(() => {
    if (!file) return "";
    return (file.canonicalAlbum ?? file.album)?.trim() ?? "";
  }, [file]);

  const youtubeWatchUrl = useMemo(
    () => (file ? resolveYoutubeWatchUrl(file, meta) : null),
    [file, meta],
  );

  const parsedDesc = useMemo(() => {
    const desc = meta?.youtube?.description || "";
    if (!desc) return { headerLines: [], creditGroups: [], footerLines: [] };

    const lines = desc.split("\n");
    const headerLines: string[] = [];
    const footerLines: string[] = [];
    const groupsMap = new Map<string, string[]>();
    const groupKeys: string[] = [];

    let inCredits = false;
    let inFooter = false;

    for (const line of lines) {
      if (!line.trim()) {
        if (!inCredits && !inFooter) headerLines.push("");
        else if (inFooter) footerLines.push("");
        continue;
      }

      if (line.includes("Auto-generated by YouTube.")) {
        inFooter = true;
        inCredits = false;
        footerLines.push(line);
        continue;
      }

      if (line.includes(":")) {
        inCredits = true;
        const [rawLabel, ...rest] = line.split(":");
        const label = rawLabel.trim().toUpperCase();
        const value = rest.join(":").trim();

        if (!groupsMap.has(label)) {
          groupsMap.set(label, []);
          groupKeys.push(label);
        }
        groupsMap.get(label)!.push(value);
      } else {
        if (inCredits) {
          inFooter = true;
          inCredits = false;
          footerLines.push(line);
        } else if (inFooter) {
          footerLines.push(line);
        } else {
          headerLines.push(line);
        }
      }
    }

    const creditGroups = groupKeys.map((k) => ({ label: k, values: groupsMap.get(k)! }));
    return { headerLines, creditGroups, footerLines };
  }, [meta?.youtube?.description]);

  const parsedDescInfo = useMemo(() => {
    let distributor = "";
    let copyright = "";
    let albumLine = "";
    const remainingHeaderLines: string[] = [];

    for (const line of parsedDesc.headerLines) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      if (trimmed.includes("Provided to YouTube by")) {
        distributor = trimmed.replace("Provided to YouTube by", "").trim();
      } else if (trimmed.includes("℗") || trimmed.toLowerCase().includes("copyright") || trimmed.includes("©")) {
        copyright = trimmed;
      } else if (trimmed.includes("·") || (album && trimmed === album)) {
        albumLine = trimmed;
      } else {
        remainingHeaderLines.push(trimmed);
      }
    }

    const catalog = albumLine ? splitCatalogLine(albumLine) : null;
    const supplementalLines = remainingHeaderLines.filter(
      (line) => !catalog || !lineDuplicatesCatalog(line, catalog.title),
    );

    return { distributor, copyright, albumLine, catalog, supplementalLines };
  }, [parsedDesc.headerLines, album]);

  if (!file) {
    return (
      <div className="flex flex-col h-full items-center justify-center gap-3 px-8 text-center text-[var(--music-text-muted)] bg-black">
        <Play size={40} strokeWidth={1.5} className="opacity-25" />
        <p className="text-sm">Track not found in library.</p>
        <button
          type="button"
          onClick={onBack}
          className="mt-2 flex items-center gap-1.5 text-xs font-medium hover:text-white transition-colors"
        >
          <ChevronLeft size={14} />
          Back
        </button>
      </div>
    );
  }

  const cover = bestCoverPath(file);
  const coverSrc = cover ? convertFileSrc(cover) : null;
  const artistKey = artistKeyFromFile(file);
  const artistDisplay = rawArtistFromFile(file);
  const albumKey = album ? albumKeyFromFile(file) : "";
  const showAlbumLink = album && albumKey && fileHasBrowsableAlbum(file, libraryTracks);

  return (
    <div className="relative flex h-full overflow-hidden bg-black text-white">
      {/* Immersive Cinematic Background */}
      {coverSrc && (
        <div className="absolute inset-0 z-0 select-none pointer-events-none" aria-hidden>
          <img
            src={coverSrc}
            alt=""
            className="w-full h-full object-cover opacity-50 blur-[100px] scale-150 transform-gpu"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-black/60 to-black" />
          <div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/40 to-black/80" />
        </div>
      )}

      {/* Main Content Area */}
      <div className="relative z-10 flex flex-col lg:flex-row w-full h-full overflow-y-auto lg:overflow-hidden rf-scrollbar">
        
        {/* Left: Hero Art (Sticky on Desktop) */}
        <div className="w-full lg:w-1/2 lg:h-full shrink-0 flex flex-col items-center justify-center p-8 lg:p-16 relative">
          <button
            type="button"
            onClick={onBack}
            className="absolute top-6 left-6 lg:top-10 lg:left-10 flex items-center gap-2 text-white/70 hover:text-white transition-colors z-20"
          >
            <ChevronLeft size={18} strokeWidth={2.5} />
            <span className="text-sm font-bold tracking-wide">Back</span>
          </button>

          <div className="relative w-full max-w-xs sm:max-w-sm lg:max-w-md xl:max-w-lg aspect-square rounded-[32px] overflow-hidden group mt-16 lg:mt-0 border border-white/5">
            {coverSrc ? (
              <img
                src={coverSrc}
                alt=""
                className="w-full h-full object-cover transition-transform duration-1000 ease-out group-hover:scale-105"
              />
            ) : (
              <div className="w-full h-full bg-white/5 flex items-center justify-center backdrop-blur-2xl">
                <Play size={80} className="text-white/10" />
              </div>
            )}
            
            {/* Hover Play Overlay */}
            <div className="absolute inset-0 flex items-center justify-center bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 backdrop-blur-[2px]">
              <button
                type="button"
                onClick={() => onPlayFile(file, [file], musicQueueSource("track", file.name))}
                className="w-24 h-24 flex items-center justify-center rounded-full bg-[var(--music-accent)] text-white hover:scale-110 active:scale-95 transition-transform duration-200"
              >
                <Play size={36} fill="currentColor" className="ml-2" />
              </button>
            </div>
          </div>
        </div>

        {/* Right: Scrolling Details & Typography */}
        <div className="w-full lg:w-1/2 lg:h-full lg:overflow-y-auto rf-scrollbar px-8 pb-24 lg:py-24 lg:pr-24 xl:pr-32 lg:flex lg:flex-col">
          <div className="flex flex-col max-w-2xl gap-8 lg:gap-12 lg:my-auto">
            
            {/* Titles Block */}
            <div className="flex flex-col gap-3 animate-fade-in" style={{ animationDelay: '100ms', animationFillMode: 'both' }}>
              <h1 className="text-5xl sm:text-6xl lg:text-7xl font-black text-white tracking-tighter leading-[1.05]">
                {file.name}
              </h1>
              
              <div className="flex flex-wrap items-center gap-4 text-xl lg:text-2xl text-white/80 font-medium">
                {artistDisplay && (
                  <button
                    type="button"
                    onClick={() => artistKey && onOpenArtist(artistKey)}
                    className="hover:text-white transition-colors"
                  >
                    {artistDisplay}
                  </button>
                )}
                {showAlbumLink && (
                  <>
                    <span className="text-white/30 text-lg">•</span>
                    <button
                      type="button"
                      onClick={() => onOpenAlbum(artistKey, albumKey)}
                      className="hover:text-white transition-colors"
                    >
                      {album}
                    </button>
                  </>
                )}
              </div>
            </div>

            {/* Primary Actions Row */}
            <div className="flex items-center gap-6 animate-fade-in" style={{ animationDelay: '200ms', animationFillMode: 'both' }}>
              <button
                type="button"
                onClick={() => onPlayFile(file, [file], musicQueueSource("track", file.name))}
                className="px-6 py-2.5 rounded-full bg-white text-black font-bold text-sm hover:scale-105 active:scale-95 transition-transform flex items-center gap-2"
              >
                <Play size={16} fill="currentColor" />
                Play Now
              </button>
              <MusicLikeButton
                file={file}
                size={24}
                className="hover:scale-110 active:scale-95 transition-transform"
              />
            </div>

            {/* Huge Stats (No Boxes, Just Typography) */}
            <div className="flex flex-wrap gap-x-12 gap-y-8 pt-6 animate-fade-in" style={{ animationDelay: '300ms', animationFillMode: 'both' }}>
              <div className="flex flex-col gap-1">
                <span className="text-4xl lg:text-5xl font-light text-white tracking-tighter">
                  {meta?.youtube?.viewCount ? (meta.youtube.viewCount / 1000000).toFixed(1) + "M" : "-"}
                </span>
                <span className="text-xs lg:text-sm text-white/50 font-medium tracking-wide uppercase">Views</span>
              </div>
              
              <div className="flex flex-col gap-1">
                <span className="text-4xl lg:text-5xl font-light text-white tracking-tighter">
                  {meta?.youtube?.likeCount ? (meta.youtube.likeCount / 1000).toFixed(0) + "K" : "-"}
                </span>
                <span className="text-xs lg:text-sm text-white/50 font-medium tracking-wide uppercase">Likes</span>
              </div>

              <div className="flex flex-col gap-1">
                <span className="text-4xl lg:text-5xl font-light text-white tracking-tighter">
                  {listenStats ? listenStats.plays : "0"}
                </span>
                <span className="text-xs lg:text-sm text-white/50 font-medium tracking-wide uppercase">Your Plays</span>
              </div>
              
              <div className="flex flex-col gap-1">
                <span className="text-4xl lg:text-5xl font-light text-white tracking-tighter">
                  {file.duration > 0 ? formatDuration(file.duration) : "-"}
                </span>
                <span className="text-xs lg:text-sm text-white/50 font-medium tracking-wide uppercase">Duration</span>
              </div>
            </div>

            {/* Release context */}
            {(parsedDescInfo.distributor
              || parsedDescInfo.catalog
              || parsedDescInfo.copyright
              || parsedDescInfo.supplementalLines.length > 0
              || parsedDesc.creditGroups.length > 0) && (
            <div className="pt-14 animate-fade-in flex flex-col gap-8" style={{ animationDelay: '400ms', animationFillMode: 'both' }}>

              {(parsedDescInfo.distributor
                || parsedDescInfo.catalog
                || parsedDescInfo.copyright
                || parsedDescInfo.supplementalLines.length > 0
                || parsedDesc.creditGroups.length > 0) && (
                <div className="flex flex-col gap-7">
                  {parsedDescInfo.distributor && (
                    <p className="text-[10px] uppercase tracking-[0.22em] text-white/35 font-semibold">
                      Provided via {parsedDescInfo.distributor}
                    </p>
                  )}

                  {parsedDescInfo.catalog && (
                    <div className="flex flex-col gap-3">
                      <p className="text-3xl sm:text-4xl lg:text-[2.75rem] font-light text-white leading-[1.12] tracking-tight">
                        {parsedDescInfo.catalog.title}
                      </p>
                      {parsedDescInfo.catalog.artist && (
                        <p className="text-lg sm:text-xl text-white/55 font-light tracking-tight">
                          {parsedDescInfo.catalog.artist}
                        </p>
                      )}
                    </div>
                  )}

                  {parsedDescInfo.supplementalLines.map((line, idx) => (
                    <p
                      key={idx}
                      className="text-xl sm:text-2xl font-light text-white/80 leading-relaxed tracking-tight max-w-xl"
                    >
                      {line}
                    </p>
                  ))}

                  {(parsedDescInfo.copyright || meta?.year) && (
                    <p className="text-sm sm:text-base text-white/40 font-light leading-relaxed max-w-xl">
                      {[parsedDescInfo.copyright, meta?.year].filter(Boolean).join(" · ")}
                    </p>
                  )}

                  {parsedDesc.creditGroups.length > 0 && (
                    <div className="pt-1">
                      <MusicTrackCredits
                        groups={parsedDesc.creditGroups}
                        trackTitle={file.name}
                        path={path}
                      />
                    </div>
                  )}
                </div>
              )}
            </div>
            )}

            {/* Archive: source + file only */}
            {(youtubeWatchUrl || file.created || file.path) && (
            <div className="pt-6 flex flex-col gap-3">
              {youtubeWatchUrl && (
                <button
                  type="button"
                  onClick={() => void openUrl(youtubeWatchUrl)}
                  className="inline-flex items-center gap-2 text-white/40 hover:text-white transition-colors duration-200 w-fit group"
                >
                  <Youtube size={15} className="text-red-500/90 group-hover:scale-105 transition-transform duration-200" />
                  <span className="text-xs font-medium tracking-tight">
                    Watch on YouTube
                  </span>
                </button>
              )}

              <div className="flex flex-col gap-2">
                {(file.created || meta?.youtube?.uploadDate || listenStats?.lastPlayed) && (
                  <p className="text-xs text-white/25 font-light">
                    {[
                      file.created
                        ? `Added ${new Date(file.created * 1000).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`
                        : null,
                      meta?.youtube?.uploadDate
                        ? `Released ${formatDateString(meta.youtube.uploadDate)}`
                        : null,
                      listenStats?.lastPlayed ? `Last played ${listenStats.lastPlayed}` : null,
                    ].filter(Boolean).join(" · ")}
                  </p>
                )}

                <button
                  type="button"
                  onClick={() => void openInFileManager(file.path)}
                  className="group flex items-center gap-2 text-white/20 hover:text-[var(--music-accent)] transition-colors text-[10px] font-mono text-left w-fit max-w-full"
                >
                  <Link size={11} strokeWidth={2} className="shrink-0 opacity-0 group-hover:opacity-100 transition-opacity duration-150" />
                  <span className="truncate group-hover:text-white/50 transition-colors">
                    {file.size ? `${(file.size / (1024 * 1024)).toFixed(1)} MB · ` : ""}
                    {file.path}
                  </span>
                </button>
              </div>
            </div>
            )}

          </div>
        </div>

      </div>
    </div>
  );
}
