//! Live CookieManager export for RuForge Internal (`browserContext: "ruforge"`).
//!
//! Reads cookies from embedded webviews sharing the `explorer-data` profile and writes a
//! Netscape cookies.txt for yt-dlp `--cookies`. Must run `cookies_for_url` inside
//! `spawn_blocking` (WebView2 deadlock on sync commands).

use std::collections::HashSet;
use std::io::Write;
use std::path::Path;

use cookie::{Cookie, Expiration};
use tauri::{AppHandle, Manager, Url};
use tempfile::NamedTempFile;

const YOUTUBE_URL: &str = "https://www.youtube.com";
const MUSIC_YOUTUBE_URL: &str = "https://music.youtube.com";
const MUSIC_EXPLORE_LABEL: &str = "music-explore-view";

#[cfg(target_os = "linux")]
const LINUX_EXPLORER_LABEL: &str = "explorer-surface";
#[cfg(not(target_os = "linux"))]
const WIN_EXPLORER_LABEL: &str = "explorer-view";

/// Keeps the temp cookies.txt on disk until dropped.
pub struct RuforgeCookieExport {
    _file: NamedTempFile,
}

impl RuforgeCookieExport {
    pub fn path(&self) -> &Path {
        self._file.path()
    }
}

fn cookie_dedupe_key(c: &Cookie<'_>) -> (String, String, String) {
    (
        c.domain_raw().unwrap_or("").to_string(),
        c.path().unwrap_or("/").to_string(),
        c.name().to_string(),
    )
}

fn netscape_expiry(c: &Cookie<'_>) -> i64 {
    match c.expires() {
        None | Some(Expiration::Session) => 0,
        Some(Expiration::DateTime(dt)) => dt.unix_timestamp().max(0),
    }
}

pub fn format_netscape_line(c: &Cookie<'_>) -> Option<String> {
    let domain_raw = c.domain_raw()?.to_string();
    let path = c.path().unwrap_or("/").to_string();
    let include_subdomains = if domain_raw.starts_with('.') {
        "TRUE"
    } else {
        "FALSE"
    };
    let http_only = c.http_only().unwrap_or(false);
    let domain_col = if http_only {
        format!("#HttpOnly_{domain_raw}")
    } else {
        domain_raw.clone()
    };
    let secure = if c.secure().unwrap_or(false) {
        "TRUE"
    } else {
        "FALSE"
    };
    Some(format!(
        "{domain_col}\t{include_subdomains}\t{path}\t{secure}\t{}\t{}\t{}",
        netscape_expiry(c),
        c.name(),
        c.value()
    ))
}

fn write_netscape_cookies(
    writer: &mut impl Write,
    cookies: &[Cookie<'static>],
) -> Result<(), String> {
    writeln!(writer, "# Netscape HTTP Cookie File")
        .map_err(|e| format!("Failed to write cookies header: {e}"))?;
    writeln!(
        writer,
        "# https://curl.se/docs/http-cookies.html\n# Generated by RuForge"
    )
    .map_err(|e| format!("Failed to write cookies header: {e}"))?;
    for c in cookies {
        if let Some(line) = format_netscape_line(c) {
            writeln!(writer, "{line}")
                .map_err(|e| format!("Failed to write cookie line: {e}"))?;
        }
    }
    Ok(())
}

fn fetch_cookies_for_urls(
    cookies_for_url: &dyn Fn(Url) -> Result<Vec<Cookie<'static>>, String>,
) -> Result<Vec<Cookie<'static>>, String> {
    let urls = [
        Url::parse(YOUTUBE_URL).map_err(|e| e.to_string())?,
        Url::parse(MUSIC_YOUTUBE_URL).map_err(|e| e.to_string())?,
    ];
    let mut out = Vec::new();
    for url in urls {
        out.extend(cookies_for_url(url)?);
    }
    Ok(out)
}

fn collect_cookies_sync(
    app: &AppHandle,
) -> Result<(Vec<Cookie<'static>>, Vec<String>, Vec<String>), String> {
    let mut found_labels = Vec::new();
    let mut missing_labels = Vec::new();
    let mut cookies = Vec::new();

    #[cfg(target_os = "linux")]
    {
        if let Some(win) = app.get_webview_window(LINUX_EXPLORER_LABEL) {
            found_labels.push(LINUX_EXPLORER_LABEL.to_string());
            cookies.extend(fetch_cookies_for_urls(&|url| {
                win.cookies_for_url(url).map_err(|e| e.to_string())
            })?);
        } else {
            missing_labels.push(LINUX_EXPLORER_LABEL.to_string());
        }
    }

    #[cfg(not(target_os = "linux"))]
    {
        if let Some(webview) = app.get_webview(WIN_EXPLORER_LABEL) {
            found_labels.push(WIN_EXPLORER_LABEL.to_string());
            cookies.extend(fetch_cookies_for_urls(&|url| {
                webview.cookies_for_url(url).map_err(|e| e.to_string())
            })?);
        } else {
            missing_labels.push(WIN_EXPLORER_LABEL.to_string());
        }
    }

    if let Some(webview) = app.get_webview(MUSIC_EXPLORE_LABEL) {
        found_labels.push(MUSIC_EXPLORE_LABEL.to_string());
        cookies.extend(fetch_cookies_for_urls(&|url| {
            webview.cookies_for_url(url).map_err(|e| e.to_string())
        })?);
    } else {
        missing_labels.push(MUSIC_EXPLORE_LABEL.to_string());
    }

    let mut seen = HashSet::new();
    cookies.retain(|c| seen.insert(cookie_dedupe_key(c)));

    Ok((cookies, found_labels, missing_labels))
}

pub async fn export_ruforge_cookies_for_ytdlp(
    app: &AppHandle,
) -> Result<RuforgeCookieExport, String> {
    let app = app.clone();
    let (cookies, found, missing) = tauri::async_runtime::spawn_blocking(move || {
        collect_cookies_sync(&app)
    })
    .await
    .map_err(|e| format!("Cookie export task failed: {e}"))??;

    if cookies.is_empty() {
        let found_text = if found.is_empty() {
            "none".to_string()
        } else {
            found.join(", ")
        };
        let missing_text = if missing.is_empty() {
            "none".to_string()
        } else {
            missing.join(", ")
        };
        return Err(format!(
            "No YouTube session cookies found in RuForge Internal browser. \
             Open Explorer or Music Explore, sign in to YouTube, then try again. \
             (webviews mounted: [{found_text}]; not mounted: [{missing_text}])"
        ));
    }

    let writable: Vec<Cookie<'static>> = cookies
        .into_iter()
        .filter(|c| format_netscape_line(c).is_some())
        .collect();
    if writable.is_empty() {
        return Err(
            "RuForge Internal browser returned cookies without usable domain metadata. \
             Open Explorer or Music Explore, sign in to YouTube, then try again."
                .to_string(),
        );
    }

    let mut file = NamedTempFile::new()
        .map_err(|e| format!("Failed to create temporary cookies file: {e}"))?;
    write_netscape_cookies(&mut file, &writable)?;
    file.flush()
        .map_err(|e| format!("Failed to flush cookies file: {e}"))?;

    Ok(RuforgeCookieExport { _file: file })
}

#[cfg(test)]
mod tests {
    use super::*;
    use cookie::Cookie;

    fn sample_cookie(
        name: &str,
        value: &str,
        domain: &str,
        http_only: bool,
        secure: bool,
    ) -> Cookie<'static> {
        let mut builder = Cookie::build((name, value)).path("/").domain(domain);
        if http_only {
            builder = builder.http_only(true);
        }
        if secure {
            builder = builder.secure(true);
        }
        builder.build().unwrap().into_owned()
    }

    #[test]
    fn netscape_session_cookie_writes_expiry_zero() {
        let c = sample_cookie("SID", "abc", ".youtube.com", false, true);
        let line = format_netscape_line(&c).expect("line");
        let parts: Vec<&str> = line.split('\t').collect();
        assert_eq!(parts.len(), 7);
        assert_eq!(parts[4], "0");
    }

    #[test]
    fn netscape_uses_domain_raw_with_leading_dot() {
        let c = sample_cookie("LOGIN_INFO", "x", ".youtube.com", true, true);
        let line = format_netscape_line(&c).expect("line");
        assert!(line.starts_with("#HttpOnly_.youtube.com\tTRUE\t"));
    }

    #[test]
    fn netscape_host_only_domain_no_subdomain_flag() {
        let mut builder = Cookie::build(("test", "1"))
            .domain("www.youtube.com")
            .path("/");
        let c = builder.build().unwrap().into_owned();
        let line = format_netscape_line(&c).expect("line");
        let parts: Vec<&str> = line.split('\t').collect();
        assert_eq!(parts[1], "FALSE");
    }

    #[test]
    fn write_netscape_includes_header_and_lines() {
        let cookies = vec![sample_cookie("SID", "v", ".youtube.com", false, true)];
        let mut buf = Vec::new();
        write_netscape_cookies(&mut buf, &cookies).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert!(text.contains("# Netscape HTTP Cookie File"));
        assert!(text.contains("SID\tv") || text.contains("SID\t"));
    }
}
