import {
  AppWindow,
  AudioWaveform,
  Bell,
  Bug,
  Captions,
  Compass,
  Download,
  Folder,
  GalleryHorizontal,
  Gauge,
  Globe,
  HardDrive,
  Headphones,
  Heart,
  Image,
  LibraryBig,
  Lightbulb,
  ListMusic,
  ListVideo,
  MessageCircle,
  MessageSquare,
  MicVocal,
  Music,
  Palette,
  PictureInPicture2,
  Play,
  Power,
  RefreshCw,
  Rss,
  Settings,
  Share,
  SkipForward,
  Tag,
  Trash2,
  Volume2,
  type LucideIcon,
} from 'lucide-react';

/** First match wins, so the more specific keywords come first. */
const AREA_ICONS: [string, LucideIcon][] = [
  ['lyric', MicVocal],
  ['island', PictureInPicture2],
  ['crossfade', AudioWaveform],
  ['sponsor', SkipForward],
  ['chapter', ListVideo],
  ['subtitle', Captions],
  ['scrub', GalleryHorizontal],
  ['comment', MessageSquare],
  ['volume', Volume2],
  ['listen', Headphones],
  ['discord', MessageCircle],
  ['channel', Rss],
  ['youtube', Globe],
  ['explore', Globe],
  ['browser', Globe],
  ['playlist', ListMusic],
  ['liked', Heart],
  ['delete', Trash2],
  ['cleanup', Trash2],
  ['storage', HardDrive],
  ['thumbnail', Image],
  ['export', Share],
  ['media', Folder],
  ['library', LibraryBig],
  ['download', Download],
  ['queue', Download],
  ['music', Music],
  ['audio', Headphones],
  ['playback', Play],
  ['player', Play],
  ['appearance', Palette],
  ['accent', Palette],
  ['radial', Compass],
  ['navigation', Compass],
  ['notification', Bell],
  ['tip', Lightbulb],
  ['onboarding', Lightbulb],
  ['chrome', AppWindow],
  ['window', AppWindow],
  ['title', AppWindow],
  ['setting', Settings],
  ['crash', Bug],
  ['debug', Bug],
  ['boot', Power],
  ['splash', Power],
  ['update', RefreshCw],
  ['install', RefreshCw],
  ['perf', Gauge],
];

export function releaseAreaIcon(area: string): LucideIcon {
  const key = area.toLowerCase();
  return AREA_ICONS.find(([word]) => key.includes(word))?.[1] ?? Tag;
}
