//! Pure Netscape cookies.txt formatting for yt-dlp `--cookies`.
//! No Tauri/WebView2 dependency — safe to unit test on any host.

use std::io::Write;

use cookie::{Cookie, Expiration};

pub fn cookie_dedupe_key(c: &Cookie<'_>) -> (String, String, String) {
    (
        c.domain_raw().unwrap_or("").to_string(),
        c.path().unwrap_or("/").to_string(),
        c.name().to_string(),
    )
}

fn netscape_expiry(c: &Cookie<'_>) -> i64 {
    match c.expires() {
        None | Some(Expiration::Session) => 0,
        Some(Expiration::DateTime(dt)) => dt.unix_timestamp().max(0),
    }
}

/// Netscape domain column and includeSubdomains flag.
fn netscape_domain_fields(c: &Cookie<'_>) -> Option<(String, &'static str)> {
    let domain = c.domain()?.to_string();
    if domain.is_empty() {
        return None;
    }
    if domain.starts_with('.') {
        return Some((domain, "TRUE"));
    }
    // Host-only cookies (www., m., etc.) — no leading dot, subdomains FALSE.
    let first_label = domain.split('.').next().unwrap_or("");
    if matches!(first_label, "www" | "m") {
        return Some((domain, "FALSE"));
    }
    // WebView2 Domain=.youtube.com is normalized to youtube.com by the cookie crate;
    // Netscape format expects .youtube.com with includeSubdomains TRUE.
    Some((format!(".{domain}"), "TRUE"))
}

/// One Netscape-format tab-separated line, or `None` if domain metadata is missing.
pub fn format_netscape_line(c: &Cookie<'_>) -> Option<String> {
    let path = c.path().unwrap_or("/").to_string();
    let (domain_col, include_subdomains) = netscape_domain_fields(c)?;
    let http_only = c.http_only().unwrap_or(false);
    let domain_col = if http_only {
        format!("#HttpOnly_{domain_col}")
    } else {
        domain_col
    };
    let secure = if c.secure().unwrap_or(false) {
        "TRUE"
    } else {
        "FALSE"
    };
    Some(format!(
        "{domain_col}\t{include_subdomains}\t{path}\t{secure}\t{}\t{}\t{}",
        netscape_expiry(c),
        c.name(),
        c.value()
    ))
}

/// Write a Netscape cookies.txt body (header + lines). Skips cookies without domain metadata.
pub fn write_netscape_cookies(
    writer: &mut impl Write,
    cookies: &[Cookie<'static>],
) -> Result<usize, String> {
    writeln!(writer, "# Netscape HTTP Cookie File")
        .map_err(|e| format!("Failed to write cookies header: {e}"))?;
    writeln!(
        writer,
        "# https://curl.se/docs/http-cookies.html\n# Generated by RuForge"
    )
    .map_err(|e| format!("Failed to write cookies header: {e}"))?;
    let mut written = 0usize;
    for c in cookies {
        if let Some(line) = format_netscape_line(c) {
            writeln!(writer, "{line}")
                .map_err(|e| format!("Failed to write cookie line: {e}"))?;
            written += 1;
        }
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;
    use cookie::Cookie;

    fn parsed_cookie(set_cookie: &str) -> Cookie<'static> {
        Cookie::parse(set_cookie).unwrap().into_owned()
    }

    #[test]
    fn netscape_session_cookie_writes_expiry_zero() {
        let c = parsed_cookie("SID=abc; Domain=.youtube.com; Path=/; Secure");
        let line = format_netscape_line(&c).expect("line");
        let parts: Vec<&str> = line.split('\t').collect();
        assert_eq!(parts.len(), 7);
        assert_eq!(parts[4], "0");
    }

    #[test]
    fn netscape_uses_domain_raw_with_leading_dot_and_subdomains_true() {
        let c = parsed_cookie("LOGIN_INFO=x; Domain=.youtube.com; Path=/; Secure; HttpOnly");
        let line = format_netscape_line(&c).expect("line");
        assert!(line.starts_with("#HttpOnly_.youtube.com\tTRUE\t"), "got: {line}");
    }

    #[test]
    fn netscape_host_only_domain_subdomains_false() {
        let c = parsed_cookie("test=1; Domain=www.youtube.com; Path=/");
        let line = format_netscape_line(&c).expect("line");
        let parts: Vec<&str> = line.split('\t').collect();
        assert_eq!(parts[1], "FALSE");
    }

    #[test]
    fn netscape_secure_true_and_false() {
        let secure = parsed_cookie("SID=v; Domain=.youtube.com; Path=/; Secure");
        let insecure = parsed_cookie("PREF=v; Domain=.youtube.com; Path=/");
        let secure_line = format_netscape_line(&secure).expect("secure");
        let insecure_line = format_netscape_line(&insecure).expect("insecure");
        assert!(secure_line.contains("\tTRUE\t0\tSID\t"));
        assert!(insecure_line.contains("\tFALSE\t0\tPREF\t"));
    }

    #[test]
    fn netscape_webview_style_builder_domain() {
        let c = Cookie::build(("SID", "v"))
            .domain(".youtube.com")
            .path("/")
            .secure(true)
            .build()
            .into_owned();
        let line = format_netscape_line(&c).expect("line");
        assert!(line.starts_with(".youtube.com\tTRUE\t"), "got: {line}");
    }

    #[test]
    fn write_netscape_includes_header_and_cookie_count() {
        let cookies = vec![parsed_cookie("SID=v; Domain=.youtube.com; Path=/; Secure")];
        let mut buf = Vec::new();
        let count = write_netscape_cookies(&mut buf, &cookies).unwrap();
        assert_eq!(count, 1);
        let text = String::from_utf8(buf).unwrap();
        assert!(text.contains("# Netscape HTTP Cookie File"));
        assert!(text.contains("SID\tv"));
    }
}
